[package]
name = "sanctions"
type = "bin"
authors = [""]

[dependencies]
date = { tag = "v0.5.6", git = "https://github.com/madztheo/noir-date.git" }
sanctions = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/exclusion-check/sanctions" }
utils = {  tag = "main", git = "https://github.com/zkpassport/circuits", directory = "src/noir/lib/utils" }