SAMPLE_DG1 = ["0", "0", "0", "0", "0", "0", "0", "68", "60", "60", "77", "85", "69", "76", "76", "69", "82", "60", "60", "74", "79", "72", "65", "78", "78", "69", "83", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "60", "49", "50", "51", "52", "53", "54", "55", "56", "57", "0", "68", "60", "60", "56", "54", "48", "50", "50", "54", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", ]

[[proofs]]
[proofs.left]
leaf = "0x253f699a00c6ebc63357e4077415ee9959fe7ce513337b8d011776896a5c9245"
leaf_index = 0x017b0c
sibling_path = [
"0x253f8f885503a23f717442608842b6e39fce3a2b43318a4eac21108f2630acfd",
"0x24bd9d48f233eda4599f95b08391873dbc640b651bdb8c99f2900903c3945aa5",
"0x1d09ff7e7dc58ad80a729c52b9b4db5afac0c32a7cc0a88fc88d10613925e37e",
"0x221def02ad071a267acb3e0f24cfe7c1f6453dc6127ada3bb5e1d469ad2087ac",
"0x200b532fe3c078eb6941d2554d08bde97d7f3dafc143c894674461385d7e4270",
"0x2cb807a839d139da23c9f56e1fd1060eb21c06281ced5d46598e3c6bc3b3e964",
"0x111905f1e5f58a9ca141698144a4c1a5d69ca3748818aa03412fa7c4ac557263",
"0x2ba10a03bb6e7b8ec592c3227ea047fe9b18ac993c6657e95fe80e8a5238a365",
"0xc26137759ff28b99639f33ca3cc45d37f7e39af7b85f270a785cb2a41c7b69",
"0x1b26d92752998e70d3ce040bf20216ef582f278d580e40504dff7a08f11af738",
"0x23a52b850cbd9bf9e63d1e322201b6123563f5673c3278ddab7cbcbe0cb58b93",
"0x0cc433606a98902e868cd95107de9aab5f028499f3cd3f05460c1b03ebcead0f",
"0x197f446b008d2c32aa138f22d322834e3d6ecdbb7693fced7fbdf75a8fc8dfe2",
"0x1bceedf9c7969411cfa6bf3682826aa9a9189f3094ab888d34a82d30f9769e3d",
"0x1b919414a47ab7f0bfb66d9311c9c237fe8e5de6c86feb38375a5f57ad4b3c8d",
"0x2b0839190b17d24db959a2913c1c96c5b87239da38771ddb5301a960cd717319",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]
[proofs.right]
leaf = "0x253f8f885503a23f717442608842b6e39fce3a2b43318a4eac21108f2630acfd"
leaf_index = 0x017b0d
sibling_path = [
"0x253f699a00c6ebc63357e4077415ee9959fe7ce513337b8d011776896a5c9245",
"0x24bd9d48f233eda4599f95b08391873dbc640b651bdb8c99f2900903c3945aa5",
"0x1d09ff7e7dc58ad80a729c52b9b4db5afac0c32a7cc0a88fc88d10613925e37e",
"0x221def02ad071a267acb3e0f24cfe7c1f6453dc6127ada3bb5e1d469ad2087ac",
"0x200b532fe3c078eb6941d2554d08bde97d7f3dafc143c894674461385d7e4270",
"0x2cb807a839d139da23c9f56e1fd1060eb21c06281ced5d46598e3c6bc3b3e964",
"0x111905f1e5f58a9ca141698144a4c1a5d69ca3748818aa03412fa7c4ac557263",
"0x2ba10a03bb6e7b8ec592c3227ea047fe9b18ac993c6657e95fe80e8a5238a365",
"0xc26137759ff28b99639f33ca3cc45d37f7e39af7b85f270a785cb2a41c7b69",
"0x1b26d92752998e70d3ce040bf20216ef582f278d580e40504dff7a08f11af738",
"0x23a52b850cbd9bf9e63d1e322201b6123563f5673c3278ddab7cbcbe0cb58b93",
"0x0cc433606a98902e868cd95107de9aab5f028499f3cd3f05460c1b03ebcead0f",
"0x197f446b008d2c32aa138f22d322834e3d6ecdbb7693fced7fbdf75a8fc8dfe2",
"0x1bceedf9c7969411cfa6bf3682826aa9a9189f3094ab888d34a82d30f9769e3d",
"0x1b919414a47ab7f0bfb66d9311c9c237fe8e5de6c86feb38375a5f57ad4b3c8d",
"0x2b0839190b17d24db959a2913c1c96c5b87239da38771ddb5301a960cd717319",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]

[[proofs]]
[proofs.left]
leaf = "0x2715dee369912c06dffb00de82ebdbe018393fe2832549646006bca89b0c8bb9"
leaf_index = 0x018dff
sibling_path = [
"0x2715aac4eb7a6dd59b7e4fe6758d1270abe5c9e101db2e1194ad39265743d2f3",
"0x0e9d5579754c1449d9c98fc18867ec54c68d91c16ab5d88c36f82a0c80180eb5",
"0x2c88c955a1fb3586aea9d7e329d085987d40b1028a5dbe3a3d125a25e90f2721",
"0x2bfb6e2b899138f75dd9036fd7be57140cf8742c1318b583d6ac2f221cf550be",
"0x289fe421b38205eef43349fcfb707ec6f0e72ceb0cc7bae88004fe6267aa039b",
"0x1ff29d538a2fbc052d3f2809f8c705089fc0b8302a4e2c74dc1d102368d9122a",
"0x024ad7f15a08183d1252ad966a115a25b158028916f000303b73af4a006abb77",
"0x124198912a248510a0c61e4007f5ac0861c9e3d4ae42af37904b6a4f3114c02d",
"0x0d665752950864b055b4faf8d53e2e37e7c404e4e06afd0d0c5e18f4038df340",
"0x211cf1ec638dec7f5800c1a59e6b693b6828046e4c791d1e44e473bd8317858d",
"0x047019dece095d8789edc34a404c2626cedf6d610cd4c306e826dbd9123bb9ea",
"0x1450ecb79b325e3fe10d27ffb2327170db18790788b02681a28b58ff7adf8113",
"0x0cfd1eff22276645730bc29de5fe7ff0289501dcb55091215eced1644409f4fa",
"0x171ff5e1b6d26a1d399ac079772f7de1e4e97bbce2b05efa902f576b8465e410",
"0x03c48d29546c20f1d98ba6547feffb80ae5c43b2b884061bb235b997f7b3e42d",
"0x2223821be1e87256af405ab0f896397559d876cf3c9da895eb12ff3b34ac2782",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]
[proofs.right]
leaf = "0x27167ebc740a079208191d018b9ba4bb608ec7ec3eb4e5470840dcad60a7ad4c"
leaf_index = 0x018e00
sibling_path = [
"0x271687d5a09de9e4cdce1acd7b4aba8f5eee656752131b239298251abe6d7fcd",
"0x2332b70579999c0e90f162789542201935696516a774486c9f82922278f0b126",
"0x0fa5e57e41d6186dc23f4dd523e920c999176d946357e4897ec6ec8485ca6696",
"0x24087f7d540eae844d4bc45834bc69003db36ec9f7a4a4810112e90fc19fe357",
"0x1e6a6b1fc5596c05b13330658c4f56b005c6ae9aa1248ba51632a879c34a505b",
"0x06a0cc5a602a7bea49add484f934edc47a3be9f5a1b478f3e18c9745e2b7064c",
"0x2e1875cfe732cf4f7e45bd00023eaf4da4ae0803469f2960a105181f57944e9a",
"0x0ecb74e3c4afa1e490a4e1e0a1e049bcff3b84990bbd2440f4404cc36a01b6a8",
"0x05a15dca04dd44c22b19f2ef1e7e991fd9347e2b2f994dfcfea793f7dd7488ae",
"0x05363c59838b94fdde9582b7c6381335a30c5d38bad54877c7c0917cdbd65338",
"0x047019dece095d8789edc34a404c2626cedf6d610cd4c306e826dbd9123bb9ea",
"0x1450ecb79b325e3fe10d27ffb2327170db18790788b02681a28b58ff7adf8113",
"0x0cfd1eff22276645730bc29de5fe7ff0289501dcb55091215eced1644409f4fa",
"0x171ff5e1b6d26a1d399ac079772f7de1e4e97bbce2b05efa902f576b8465e410",
"0x03c48d29546c20f1d98ba6547feffb80ae5c43b2b884061bb235b997f7b3e42d",
"0x2223821be1e87256af405ab0f896397559d876cf3c9da895eb12ff3b34ac2782",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]

[[proofs]]

[proofs.left]
leaf = "0x0b967d00707fa8f87666c746080b5bedfc8de186b199a5102af442913586570b"
leaf_index = 0x7546
sibling_path = [
"0x0b96b361bd2c799daf6a703ae2c2ad8ad053b1b60ce0ab50e41c752b803bbbbb",
"0x2ffb80eb5ff5b253f5348b1d9142a12518e2d35b5ae454f593a1a01fc023ae23",
"0x03929ce4ac6c7a89d9bf35e9cd1c8b26a4da219eb7900887c1e2f03decb997fc",
"0x1dbcff48db0644f7e29d122345648440c5f829f51f1a4eede69c1df599fdfba8",
"0x20616bb34b4b996ea4df0fdb3a9a2bb2cc91ec727966ac4c05e8a60e4df4cd56",
"0x2e1eb832aff9ff191638526aa1558c406a49b4c62e3dde14eea39d672f1f3941",
"0x12cc15a4b6c039fa980abab31fb04d5ac570af16ea979493a7a84e0bedb92bbd",
"0x0ec93ac9cfe21ddfe707217fe63bf5688564af2928802715df7226182343ef62",
"0x2e27bece891ccdc9eed1293d78556795653c9fc93f071823569c48fc68389a",
"0x0236f9f3f6f66c33d857fb37b17e6c1ead6e501e7d162968589cdc760478b74a",
"0x026cc0eeb12b583b9e06019d82f40810f4e1e632db4dce6b7dff0b91b4cb793f",
"0x2d0ed97cfc99e2541ace2819ee253313cdbe87d204a3cc99540ff4ccdd913da1",
"0x5c0d4aa3e474f14349496df467eb4220bcfbc5bd2c638f11b6ec4e91480264",
"0x26e8eaf91fd15af142d37370c9699889a7646daee9325d36334984383124c3d3",
"0x26676ac0091e8254a9de4aaaadd278c415cc7fb9ef7648ebd7c4d43a556655a8",
"0x0da41f8eaca0248129c5e7991b1795c6a5bd9ac3eb152a5283430bf62750f5f7",
"0x29214fc509701a92d870f6b965c4ba448c59edef55fb72dc84eb949cc482223a",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]

[proofs.right]
leaf = "0x0b96b361bd2c799daf6a703ae2c2ad8ad053b1b60ce0ab50e41c752b803bbbbb"
leaf_index = 0x7547
sibling_path = [
"0x0b967d00707fa8f87666c746080b5bedfc8de186b199a5102af442913586570b",
"0x2ffb80eb5ff5b253f5348b1d9142a12518e2d35b5ae454f593a1a01fc023ae23",
"0x03929ce4ac6c7a89d9bf35e9cd1c8b26a4da219eb7900887c1e2f03decb997fc",
"0x1dbcff48db0644f7e29d122345648440c5f829f51f1a4eede69c1df599fdfba8",
"0x20616bb34b4b996ea4df0fdb3a9a2bb2cc91ec727966ac4c05e8a60e4df4cd56",
"0x2e1eb832aff9ff191638526aa1558c406a49b4c62e3dde14eea39d672f1f3941",
"0x12cc15a4b6c039fa980abab31fb04d5ac570af16ea979493a7a84e0bedb92bbd",
"0x0ec93ac9cfe21ddfe707217fe63bf5688564af2928802715df7226182343ef62",
"0x2e27bece891ccdc9eed1293d78556795653c9fc93f071823569c48fc68389a",
"0x0236f9f3f6f66c33d857fb37b17e6c1ead6e501e7d162968589cdc760478b74a",
"0x026cc0eeb12b583b9e06019d82f40810f4e1e632db4dce6b7dff0b91b4cb793f",
"0x2d0ed97cfc99e2541ace2819ee253313cdbe87d204a3cc99540ff4ccdd913da1",
"0x5c0d4aa3e474f14349496df467eb4220bcfbc5bd2c638f11b6ec4e91480264",
"0x26e8eaf91fd15af142d37370c9699889a7646daee9325d36334984383124c3d3",
"0x26676ac0091e8254a9de4aaaadd278c415cc7fb9ef7648ebd7c4d43a556655a8",
"0x0da41f8eaca0248129c5e7991b1795c6a5bd9ac3eb152a5283430bf62750f5f7",
"0x29214fc509701a92d870f6b965c4ba448c59edef55fb72dc84eb949cc482223a",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]

[[proofs]]
[proofs.left]
leaf = "0x1de48fd8861a6646bccec1fb50e0cce9a60eed57a15f62367b47794dfdd5b23b"
leaf_index = 0x013069
sibling_path = [
"0x1de4757f6d8b1626b0663afa02ec2ea1d76bc4d923b4c21d565792065b36e8a4",
"0x01c37e1c2c4e264eb3cfebd34c2d8f16c50f040c0ce67061db462ac345fc567c",
"0x0f81d90e96a6b05bec5fbff7770fa4ff4b4f427d22a72f7209d3760e58a9da6a",
"0x16359b5ed3a359f460043ce5d08a8e914946a9e5a88e4261f6a24bf492b39a33",
"0x030dc0c920023d7bb3be40c09b49957d084cb7246842b6ae273265bd409f60db",
"0x20c2630a749018628282ad6c7febfaf275c398285b48c4d2caf8fa72a2de158e",
"0x2a06f4daf252bc41fec230459c6a2e3aad29cf25acfd9206746c125155212f57",
"0x04d41d43a2cab6be8cf40febf1513ffc27c7f4e8da52fc43df4e46e0aca69b13",
"0x231868eae35703375b6270ef79dc5c6dd223c74eea7625a1032a3ac91bad4bba",
"0x1a68cae0db26b6e1996b8a3bc28e7ffdf242e5fefa8a2fa32e9b73ab52acda00",
"0x261b088f74920c62d825322b7e76fccf8fc7cc42f79f2a9067912ff9c64815a5",
"0x26a82bce9ea392fad2f86caba9d1d592dbf754f5fb1ce4cc109e92653c3b1ba9",
"0x09c5da1b2961d64f90e6962f8b34143822465f6d2d9f676d00695e2cfdf92283",
"0x0c6cd5da59fc4b4f36d381eb28f40e7a9ca2e594a282e99c535903398158fdfa",
"0x056454165af4fcc5417dc545512e710fd841235efa0ab58794eb6a536a34f99b",
"0x2b0839190b17d24db959a2913c1c96c5b87239da38771ddb5301a960cd717319",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]
[proofs.right]
leaf = "0x1de4daf8c21b62129269125f6c5e311ad86236b353b3be908a7d1ffccb1d0f3d"
leaf_index = 0x01306a
sibling_path = [
"0x1de4e639a5beb797c0c632d3ecf204662a64ea162d34cf55cebfecef44859979",
"0x20ad907ed4fcd72a243148d158b64bfd8399b3a10e72aa32fa028bab25bd769d",
"0x0f81d90e96a6b05bec5fbff7770fa4ff4b4f427d22a72f7209d3760e58a9da6a",
"0x16359b5ed3a359f460043ce5d08a8e914946a9e5a88e4261f6a24bf492b39a33",
"0x030dc0c920023d7bb3be40c09b49957d084cb7246842b6ae273265bd409f60db",
"0x20c2630a749018628282ad6c7febfaf275c398285b48c4d2caf8fa72a2de158e",
"0x2a06f4daf252bc41fec230459c6a2e3aad29cf25acfd9206746c125155212f57",
"0x04d41d43a2cab6be8cf40febf1513ffc27c7f4e8da52fc43df4e46e0aca69b13",
"0x231868eae35703375b6270ef79dc5c6dd223c74eea7625a1032a3ac91bad4bba",
"0x1a68cae0db26b6e1996b8a3bc28e7ffdf242e5fefa8a2fa32e9b73ab52acda00",
"0x261b088f74920c62d825322b7e76fccf8fc7cc42f79f2a9067912ff9c64815a5",
"0x26a82bce9ea392fad2f86caba9d1d592dbf754f5fb1ce4cc109e92653c3b1ba9",
"0x09c5da1b2961d64f90e6962f8b34143822465f6d2d9f676d00695e2cfdf92283",
"0x0c6cd5da59fc4b4f36d381eb28f40e7a9ca2e594a282e99c535903398158fdfa",
"0x056454165af4fcc5417dc545512e710fd841235efa0ab58794eb6a536a34f99b",
"0x2b0839190b17d24db959a2913c1c96c5b87239da38771ddb5301a960cd717319",
"0x1bb6ae667fd0398f579f9d3cc551a053a1ebff652441842f671cf907a2ef21",
"0x071d7627ae3b2eabda8a810227bf04206370ac78dbf6c372380182dbd3711fe3",
]